services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse_proxy_container
    ports:
      - 3005:3005
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bottle_postgres_network

  python:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bottlesite_container
    volumes:
      - ./:/app
    networks:
      - bottle_postgres_network

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: company_postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/postgres.sql:/docker-entrypoint-initdb.d/sqlite_dump.sql
    networks:
      - bottle_postgres_network

networks:
  bottle_postgres_network:
